version: '1.0'
name: node-fullstack-pipeline
displayName: "Node全栈构建推送流水线"




triggers:
  manual: {}

variables:
  REGISTRY: "crpi-1vp5deeta128cxtu.cn-beijing.personal.cr.aliyuncs.com"
  IMAGE_NAME: "${REGISTRY}/my-app-flyme/node-fullstack-skeleton"
  IMAGE_TAG: ${GIT_COMMIT}
  COMPOSE_WAIT_TIMEOUT: "60"

stages:
  - stage:
      name: build_stage
      displayName: "构建并推送镜像到ACR"
      steps:
        - step: build@docker
          name: docker_build_push
          displayName: "Docker Build & Push ACR"
          inputs:
            dockerfile: ./Dockerfile
            image: ${IMAGE_NAME}:${IMAGE_TAG}
            registry: ${REGISTRY}
            registryCredential:
              username: ${REGISTRY_USER}
              password: ${REGISTRY_PASSWORD}

# 暂时注释部署阶段，无ECS不要启用
#  - stage:
#      name: deploy_stage
#      displayName: "SSH远程部署到ECS"
#      needs: [ build_stage ]
#      steps:
#        - step: run@shell
#          name: remote_deploy
#          displayName: "ECS pull镜像 + docker compose部署"
#          inputs:
#            script: |
#               ...
